# Generated by Django 4.2.5 on 2023-10-25 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('Horas', models.IntegerField()),
                ('puntaje', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Hoja1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.IntegerField(unique=True)),
                ('nacimiento', models.DateField()),
                ('ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Hoja2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=40)),
                ('altura', models.IntegerField()),
                ('localidad', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=40)),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.hoja1', to_field='dni')),
            ],
        ),
        migrations.DeleteModel(
            name='Prueba',
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='dni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.hoja1', to_field='dni'),
        ),
    ]
